Azine\EmailBundle\Entity\Notification:
  type: entity
  repositoryClass: Azine\EmailBundle\Entity\Repositories\NotificationRepository
  table: notification
  fields:
    id:                                                         # ID of the notification
      type: integer(9)
      id: true
      generator:
        strategy: AUTO
    recipient_id:        { type: integer(9)   }                 # recipient id
    title:               { type: string(255)  }                 # subject for the notification item
    content:             { type: text         }                 # content of the notification
    variables:           { type: json_array, nullable: true }   # array of template-variables encoded as JSON
    template:            { type: string(255)  }                 # the twig template to be used to render the txt and html-version of this notification
    send_immediately:    { type: boolean      }                 # true if the email should be sent a.s.a.p. and not joined with other notifications
    importance:          { type: integer(2)   }                 # importance level of the message, in compound messages, important messages are at the top of the email. notifications with the same importance are ordered by creation date/time.
    sent:                { type: datetime,  nullable: true }     # Date when the notification was sent
    created:             { type: datetime,  nullable: false}     # Date when the notification was created

  lifecycleCallbacks:
    prePersist: [setCreatedValue]
