Azine\EmailBundle\Entity\SentEmail:
    type: entity
    table: sent_email
    repositoryClass: Azine\EmailBundle\Entity\Repositories\SentEmailRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        recipients:  { type: array, nullable: true  } # array of recipients, can be null, if the mail was/is for everyone => public
        template:    { type: string, length: '127'  } # twig template-id of the wrapper-template, without the endings (=> e.g. "AzineEmailBundle::baseEmailLayout")
        variables:   { type: array                  } # array with all the variables used to render the email
        sent:        { type: datetime               } # date & time the email was sent
        token:       { type: string, length: 25     } # non-guessable token to identify the email.

    lifecycleCallbacks: {}
