##################################################################
## Web-View routes
##################################################################
# route for users to see emails
azine_email_webview:
    path:  /email/webview/{token}
    defaults: { _controller: "AzineEmailBundle:AzineEmailTemplate:webView" }

# route for images that were embeded in emails and now must be shown in web-view
azine_email_serve_template_image:
    path:  /email/image/{folderKey}/{filename}
    defaults: { _controller: "AzineEmailBundle:AzineEmailTemplate:serveImage"}

# index with all the email-templates you configured in you implementation of WebViewServiceInterface
azine_email_template_index:
    path:  /admin/email/
    defaults: { _controller: "AzineEmailBundle:AzineEmailTemplate:index" }

# preview of a template filled with dummy-data ... this should probably only be accessible by admins
azine_email_web_preview:
    path:  /admin/email/webpreview/{template}/{format}
    defaults: { _controller: "AzineEmailBundle:AzineEmailTemplate:webPreView", format : null }

# route to send test-mails filled with dummy-data ... this should probably only be accessible by admins
azine_email_send_test_email:
    path:  /admin/email/send-test-email-for/{template}/to/{email}
    defaults: { _controller: "AzineEmailBundle:AzineEmailTemplate:sendTestEmail", email: null}

azine_email_test_sent_email_spam_score:
    path:  /admin/email/test-sent-email-spam-score
    defaults: { _controller: "AzineEmailBundle:AzineEmailTemplate:checkSpamScoreOfSentEmail" }
