azine_email_webview:
    path: /email/webview/{token}
    controller: Azine\EmailBundle\Controller\AzineEmailTemplateController::webViewAction
    methods: [GET]

azine_email_template_index:
    path: /email/templates
    controller: Azine\EmailBundle\Controller\AzineEmailTemplateController::indexAction
    methods: [GET]

azine_email_web_preview:
    path: /email/templates/webview/{template}/{format}
    controller: Azine\EmailBundle\Controller\AzineEmailTemplateController::webPreViewAction
    defaults:
        format: html
    requirements:
        format: html|txt
    methods: [GET]

azine_email_spam_score:
    path: /email/spam-score
    controller: Azine\EmailBundle\Controller\AzineEmailTemplateController::checkSpamScoreOfSentEmailAction
    methods: [POST]

azine_email_send_test_mail:
    path: /email/templates/send-test/{template}/{email}
    controller: Azine\EmailBundle\Controller\AzineEmailTemplateController::sendTestEmailAction
    methods: [GET, POST]

azine_email_serve_template_image:
    path: /email/templates/image/{folderKey}/{filename}
    controller: Azine\EmailBundle\Controller\AzineEmailTemplateController::serveImageAction
    requirements:
        filename: .+
    methods: [GET]
