<?php

declare(strict_types=1);

namespace Azine\EmailBundle\DependencyInjection;

use Azine\EmailBundle\Services\AzineTemplateProvider;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('azine_email');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->scalarNode(AzineEmailExtension::RECIPIENT_CLASS)
                    ->defaultValue('Acme\\SomeBundle\\Entity\\User')
                ->end()
                ->scalarNode(AzineEmailExtension::RECIPIENT_NEWSLETTER_FIELD)
                    ->defaultValue('newsletter')
                ->end()
                ->scalarNode(AzineEmailExtension::NOTIFIER_SERVICE)
                    ->defaultValue('azine_email.example.notifier_service')
                ->end()
                ->scalarNode(AzineEmailExtension::TEMPLATE_PROVIDER)
                    ->defaultValue('azine_email.example.template_provider')
                ->end()
                ->scalarNode(AzineEmailExtension::RECIPIENT_PROVIDER)
                    ->defaultValue('azine_email.default.recipient_provider')
                ->end()
                ->scalarNode(AzineEmailExtension::TEMPLATE_TWIG_MAILER)
                    ->defaultValue('azine_email.default.template_twig_mailer')
                ->end()
                ->scalarNode(AzineEmailExtension::TEMPLATE_TWIG_SWIFT_MAILER)
                    ->defaultNull()
                    ->info('Deprecated alias for template_twig_mailer.')
                ->end()
                ->scalarNode(AzineEmailExtension::IMMEDIATE_MAILER_SERVICE)
                    ->defaultValue('mailer')
                    ->info('Symfony Mailer service used for emails flagged for immediate delivery.')
                ->end()
                ->arrayNode(AzineEmailExtension::NO_REPLY)
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode(AzineEmailExtension::NO_REPLY_EMAIL_ADDRESS)
                            ->defaultValue('no-reply@example.com')
                        ->end()
                        ->scalarNode(AzineEmailExtension::NO_REPLY_EMAIL_NAME)
                            ->defaultValue('notification daemon')
                        ->end()
                    ->end()
                ->end()
                ->scalarNode(AzineEmailExtension::TEMPLATE_IMAGE_DIR)
                    ->defaultValue('%kernel.project_dir%/vendor/azine/email-bundle/Resources/htmlTemplateImages/')
                ->end()
                ->arrayNode(AzineEmailExtension::ALLOWED_IMAGES_FOLDERS)
                    ->scalarPrototype()->end()
                    ->defaultValue([])
                ->end()
                ->arrayNode(AzineEmailExtension::NEWSLETTER)
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode(AzineEmailExtension::NEWSLETTER_INTERVAL)
                            ->min(1)
                            ->defaultValue(14)
                        ->end()
                        ->scalarNode(AzineEmailExtension::NEWSLETTER_SEND_TIME)
                            ->defaultValue('10:00')
                            ->validate()
                                ->ifTrue(static fn (mixed $value): bool => 1 !== preg_match('/^(?:[01]\\d|2[0-3]):[0-5]\\d$/', (string) $value))
                                ->thenInvalid('Expected a 24-hour HH:MM time, got "%s".')
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode(AzineEmailExtension::TEMPLATES)
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode(AzineEmailExtension::NEWSLETTER_TEMPLATE)
                            ->defaultValue(AzineTemplateProvider::NEWSLETTER_TEMPLATE)
                        ->end()
                        ->scalarNode(AzineEmailExtension::NOTIFICATIONS_TEMPLATE)
                            ->defaultValue(AzineTemplateProvider::NOTIFICATIONS_TEMPLATE)
                        ->end()
                        ->scalarNode(AzineEmailExtension::CONTENT_ITEM_TEMPLATE)
                            ->defaultValue(AzineTemplateProvider::CONTENT_ITEM_MESSAGE_TEMPLATE)
                        ->end()
                    ->end()
                ->end()
                ->scalarNode(AzineEmailExtension::TRACKING_PARAM_CAMPAIGN_NAME)->defaultValue('utm_campaign')->end()
                ->scalarNode(AzineEmailExtension::TRACKING_PARAM_CAMPAIGN_TERM)->defaultValue('utm_term')->end()
                ->scalarNode(AzineEmailExtension::TRACKING_PARAM_CAMPAIGN_CONTENT)->defaultValue('utm_content')->end()
                ->scalarNode(AzineEmailExtension::TRACKING_PARAM_CAMPAIGN_MEDIUM)->defaultValue('utm_medium')->end()
                ->scalarNode(AzineEmailExtension::TRACKING_PARAM_CAMPAIGN_SOURCE)->defaultValue('utm_source')->end()
                ->scalarNode(AzineEmailExtension::EMAIL_TRACKING_BASE_URL)->defaultNull()->end()
                ->scalarNode(AzineEmailExtension::EMAIL_TRACKING_CODE_BUILDER)
                    ->defaultValue('azine.email.open.tracking.code.builder.ga.or.piwik')
                ->end()
                ->arrayNode(AzineEmailExtension::DOMAINS_FOR_TRACKING)
                    ->scalarPrototype()->end()
                    ->defaultValue([])
                ->end()
                ->integerNode(AzineEmailExtension::WEB_VIEW_RETENTION)
                    ->min(1)
                    ->defaultValue(90)
                ->end()
                ->scalarNode(AzineEmailExtension::WEB_VIEW_SERVICE)
                    ->defaultValue('azine_email.example.web_view_service')
                ->end()
                ->scalarNode(AzineEmailExtension::SPAM_CHECK_ENDPOINT)
                    ->cannotBeEmpty()
                    ->defaultValue('https://spamcheck.postmarkapp.com/filter')
                    ->validate()
                        ->ifTrue(static fn (mixed $value): bool => !str_starts_with((string) $value, 'https://'))
                        ->thenInvalid('The spam-check endpoint must use HTTPS.')
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
